#!/usr/local/git/perl/bin/perl
#
#
# Copyright  (c) 2001,2002  Oracle Corporation All rights reserved 
#
#  $Id: testop,v 1.1 2002/06/11 23:11:48 ajdsouza Exp $ 
#
#  $Log: testop,v $
#  Revision 1.1  2002/06/11 23:11:48  ajdsouza
#  *** empty log message ***
#
#
#
#
# NAME  
#	 tststop
#
# DESC 
#	print output of stormon scripts to STDOUT in mozart format
#
# FUNCTIONS
#
#
# NOTES
#
#
# MODIFIED	(MM/DD/YY)
#
#

use strict;
use warnings;
use Monitor::Storage;


print "**************************** FILESYSTEMS ********************\n";
files();

print "**************************** VOLUMES ********************\n";
volumes();

print "************************ SOFTWARE RAID ********************\n";
swraid();

print "***************************** DISKS ********************\n";
disks();

