#!/usr/local/git/perl/bin/perl
#
# Copyright  (c) 2001,2002  Oracle Corporation All rights reserved
#
#  $Id: testblkload,v 1.8 2002/08/05 17:01:34 ajdsouza Exp $ 
#
#  $Log: testblkload,v $
#  Revision 1.8  2002/08/05 17:01:34  ajdsouza
#  *** empty log message ***
#
#  Revision 1.7  2002/06/14 21:27:39  ajdsouza
#  *** empty log message ***
#
#  Revision 1.6  2002/06/14 20:33:12  ajdsouza
#  *** empty log message ***
#
#  Revision 1.5  2002/06/14 20:28:38  ajdsouza
#  c
#
#  Revision 1.4  2002/06/14 20:27:24  ajdsouza
#  *** empty log message ***
#
#  Revision 1.3  2002/06/14 20:25:00  ajdsouza
#  *** empty log message ***
#
#  Revision 1.2  2002/06/14 18:28:00  ajdsouza
#  *** empty log message ***
#
#  Revision 1.1  2002/06/14 16:33:51  ajdsouza
#  *** empty log message ***
#
#
#
# NAME  
#	testblkload
#
# DESC 
#
# Test multiple simultaneous loads into the mgmt_metrics table for 9i oem
#
#
# FUNCTIONS
#
#
# NOTES
#
#
# MODIFIED	(MM/DD/YY)
# ajdsouza	06/14/02 - Created


use strict;
use warnings;
use POSIX ":sys_wait_h";

	
my @databases =
    (
     {
	 name=> 'db1',
       	 username => "system", 
	 password=>"manager",
	 address=>"(DESCRIPTION=(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = dlsun1170)(PORT = 1531)))(CONNECT_DATA=(SID=EMD)(SERVER=DEDICATED)))"
	 },
     {	 
	 name => 'db2',
	 username => "system", 
	 password=>"manager",
	 address=>"(DESCRIPTION=(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = dlsun1170)(PORT = 1531)))(CONNECT_DATA=(SID=EMD)(SERVER=DEDICATED)))"
	 }
     );


# Repository connection
$ENV{UPLOAD_DB_USER}='storage_test';
$ENV{UPLOAD_DB_PASSWORD}='storage_test';
$ENV{UPLOAD_DB_TNS}="(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(Host=138.1.160.78)(Port=1521)))(CONNECT_DATA=(SID=emniap)))";

for (0..1){

	my $n = $_ * 50;

    for ((21+$n)..(50+$n)){	
    
	my $hostname = "target\_$_";

	$ENV{EM_TARGET_NAME} = $hostname;
	$ENV{EM_TARGET_TYPE} ='oracle_sysman_node';
  
	defined( my $pid = fork ) or die " Failed to fork the child process for $ENV{EM_TARGET_NAME}";

	if ( $pid ){
	    
	    waitpid($pid,&WNOHANG);

	}
	else {
	    
	    print "Target Name =  $ENV{EM_TARGET_NAME} \n";
	    
	    `/usr/local/git/oem/storage/stormon`; 
	    
#Go thru the target structure and upload metrics to the repository      
	    
	    foreach ( @databases )
	    {
		my %dbinfo = %$_;
		
		$ENV{EM_TARGET_NAME}="$hostname\_$dbinfo{name}";
		$ENV{EM_TARGET_TYPE}='oracle_sysman_database';
		$ENV{EM_TARGET_USERNAME}=$dbinfo{username};
		$ENV{EM_TARGET_PASSWORD}=$dbinfo{password};
		$ENV{EM_TARGET_ADDRESS}=$dbinfo{address};
		
		`/usr/local/git/oem/storage/stormon`;
	    }
	    
	    exit 0;
	}	
	
    }
    
}
