#!/bin/sh

PERL5LIB=$SRCHOME/emagent/sysman/admin/scripts:$SRCHOME/perl/lib:$SRCHOME/perl/lib/site_perl;export PERL5LIB
EMAGENT_PERL_TRACE_LEVEL=0; export EMAGENT_PERL_TRACE_LEVEL
EMAGENT_PERL_TRACE_DIR=$SRCHOME/emdw/sysman/log; export EMAGENT_PERL_TRACE_DIR

EM_STORAGE_SHOW_ALL_MSGS_STDOUT=YES; export EM_STORAGE_SHOW_ALL_MSGS_STDOUT
EM_STORAGE_RMODE=CAPTURE;export EM_STORAGE_RMODE
EM_STORAGE_TEST_DEPOT=${HOME}/stormon/test;export EM_STORAGE_TEST_DEPOT
EM_STORAGE_TEST_SUBDIR=staca31_test1;export EM_STORAGE_TEST_SUBDIR
EM_AGENT_STATE_DIR=${HOME}/stormon/test;export EM_AGENT_STATE_DIR

rm ${EM_AGENT_STATE_DIR}/nmhs/*
rm ${EM_STORAGE_TEST_DEPOT}/${EM_STORAGE_TEST_SUBDIR}/*

#$SRCHOME/perl/bin/perl tst
$SRCHOME/perl/bin/perl chk

#$SRCHOME/perl/bin/perl tnmhsrcmd
