#!/usr/local/git/perl/bin/perl
#
# Copyright  (c) 2001,2002  Oracle Corporation All rights reserved
#
#  $Id: addmetrics,v 1.3 2003/10/09 22:32:31 ajdsouza Exp $ 
#
#
# NAME  
#	 addmetrics
#
# DESC 
# 	Add metrics into the mgmt_metrics table for a target type by 
# reading the ../doc/metrics.txt file
#
#
# FUNCTIONS
#
#
# NOTES
#
#
# MODIFIED	(MM/DD/YY)
# ajdsouza	04/04/04 - All metrics are to be for targettype oracle_sysman_node
# ajdsouza	04/03/02 - Created



use strict;
use DBI;


# Connect to the repository

my $rep_username = qw/storage_rep/;
my $rep_password = qw/storage_rep/;
my $rep_address = "(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(Host=rmsun11.us.oracle.com)(Port=1521)))(CONNECT_DATA=(SID=emap)))";
my %attr = (AutoCommit => 0, RaiseError => 1);

my $dbh = DBI->connect("dbi:Oracle:".$rep_address,$rep_username,$rep_password,\%attr) or die $DBI::errstr;

my $sth0 = $dbh->prepare("SELECT MAX(metric_guid) maxmg FROM MGMT_METRICS") or die $DBI::errstr;

my $sth1 = $dbh->prepare("SELECT 'X' FROM MGMT_METRICS WHERE TARGET_TYPE = :1 AND METRIC_NAME = :2 AND METRIC_COLUMN = :3") or die $DBI::errstr;
my $sth = $dbh->prepare('INSERT INTO MGMT_METRICS (TARGET_TYPE,METRIC_NAME,METRIC_GUID,METRIC_COLUMN) VALUES(:1,:2,:3,:4)') or die $DBI::errstr;

# Get the max metric guid
$sth0->execute or die $dbh->errstr;

my @maxmq = $sth0->fetchrow_array or die;

$sth0->finish;

# Read the metrics from metrics.txt
open(METRICS,"../../doc/metrics.txt") or die " Failed to open load_metrics.txt file $! ";

my $metricname;
my $metricid;
my $targettype = qw/oracle_sysman_node/;

# Start the metric guid from the max metric_guid
$metricid = $maxmq[0] + 1;

while (<METRICS>)
{
    next if /----/ or /Metric\s+Column/i or /^\s*$/;
       
    s/^\s+|\s+$//g;

    my @fields = split;

    if ( /^Metric\s+Name/i )
    {
	$metricname = $fields[2];
	$metricid += 500;
	
	next;
    }

# Dont load the key metric column
    next if ( $fields[0] eq $metricname.'_key' );
       	
    $sth1->execute($targettype,$metricname,$fields[0]) or die $dbh->errstr;    

    next if $sth1->fetchrow_array; 

    print "$targettype $metricname $metricid $fields[0] \n";

   $sth->execute($targettype,$metricname,$metricid,$fields[0]) or die $dbh->errstr;

    $metricid++;

}

$sth->finish;

$sth1->finish;

close(METRICS);

$dbh->commit or die $dbh->errstr;

$dbh->disconnect;


