SET PAGESIZE 0
SET LINESIZE 80 
SPOOL data.txt
SELECT TARGET_GUID||CHR(9)||KEY_VALUE||CHR(9)||STORAGE_LAYER||CHR(9)||ENTITY_TYPE||CHR(9)||SIZEB||CHR(9)||USEDB||CHR(9)||FREEB||CHR(9)||EM_QUERY_FLAG||CHR(9)||NVL(GLOBAL_UNIQUE_ID,'-')||CHR(9)||' ?' FROM mgmt$storage_report_data
/
SELECT TARGET_GUID||CHR(9)||KEY_VALUE||CHR(9)||NVL(PARENT_KEY_VALUE,'-')||CHR(9)||' ?' FROM MGMT$STORAGE_REPORT_KEYS
/
SPOOL OFF;


